name: HelloWorld

on:
  push:
    branches:
      - main
      - develop

jobs:
  welcome:
     runs-on: ubuntu-latest

     steps:
       - name: Download You Code
         uses: actions/checkout@v2

       - name: Say something
         run: echo "Hello World" 
         
  hello-branches:
      runs-on: ubuntu-latest

      steps:
      - name: Download your Code
        uses: actions/checkout@v2

      - name: Verify develop branch
        if: ${{ github.ref == 'refs/heads/develop'}}
        run: echo "Hello Develop"

      - name: Verify main develop
        if: ${{ github.ref == 'refs/heads/main'}}
        run: echo "Hello main"
      
    
  

